"""removed email, added username

Revision ID: e26c8282cff2
Revises: da154e00f112
Create Date: 2020-11-29 12:47:43.842088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26c8282cff2'
down_revision = 'da154e00f112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
